apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-all
spec:
  types:
  - Ingress
  - Egress
  ingress:
  - action: Allow
    source: {}
    destination: {}
  egress:
  - action: Allow
    source: {}
    destination: {}
