---
- name: make sure the kube config directory exits
  file:
    path: "{{ kube_conf_dir }}"
    state: directory
    mode: u=rwx,g=r-x,o=r-x

- name: Write kube config file
  template: src=config.j2 dest="{{ kube_conf_file }}"

#- name: make sure the harbor cert key directory exits
#  file:
#    path: "{{ harbor_cert_dir }}"
#    state: directory
#    mode: u=rwx,g=r-x,o=r-x
#
#- name: Write harbor ca file
#  copy:
#    src: harbor-ca.crt
#    dest: "{{ harbor_cert_dir }}/ca.crt"
#  tags: configure


- name: copy ha cert
  copy:
    src: "{{ ha_cert_dir }}"
    dest: /etc/
  tags: configure

- name: reload systemd
  command: systemctl --system daemon-reload
