---

#- name: set pamc cloud repo
#  template: src=pamccloudrepo.repo.j2 dest=/etc/yum.repos.d/pamccloudrepo.repo
#  tags: install


- name: Install kube-proxy
  copy:
    src=kubectl
    dest=/usr/local/bin
    mode=0755
  tags: install
