---

- name: Install kube-scheduler
  copy: 
    src=kube-scheduler
    dest=/usr/local/bin/
    mode=0755
  tags: install

- name: update kube-scheduler.service
  template: src=kube-scheduler.service dest=/usr/lib/systemd/system/kube-scheduler.service
  notify:
    - reload systemd
    - kube-scheduler restart service
  tags: configure

- name: reload systemd
  command: systemctl daemon-reload

- name: Start kube-scheduler
  service: name=kube-scheduler state=started
  tags: configure

- name: Enable kube-scheduler
  service: name=kube-scheduler enabled=yes
