---

- name: Install kube-controller-manager
  copy: 
    src=kube-controller-manager
    dest=/usr/local/bin/
    mode=0755
  tags: install

- name: update kube-controller-manager.service
  template: src=kube-controller-manager.service dest=/usr/lib/systemd/system/kube-controller-manager.service
  notify:
    - reload systemd
    - kube-controller-manager restart service
  tags: configure

- name: reload systemd
  command: systemctl daemon-reload

- name: Start kube-controller-manager
  service: name=kube-controller-manager state=started
  tags: configure

- name: Enable kube-controller-manager
  service: name=kube-controller-manager enabled=yes
