---

#- name: set pamc cloud repo
#  template: src=pamccloudrepo.repo.j2 dest=/etc/yum.repos.d/pamccloudrepo.repo
#  tags: install


- name: Install kubelet
  copy: 
    src=kubelet
    dest=/usr/local/bin/
    mode=0755
  tags: install

- name: make sure the kube-proxy work directory exits
  file:
    path: /var/lib/kubelet
    state: directory
    mode: u=rwx,g=r-x,o=r-x

- name: update kubelet.service
  template: src=kubelet.service dest=/usr/lib/systemd/system/kubelet.service
  notify:
    - reload systemd
    - kubelet restart service
  tags: configure

- name: reload systemd
  command: systemctl daemon-reload

- name: Start kubelet
  service: name=kubelet state=started
  tags: configure

- name: Enable kubelet
  service: name=kubelet enabled=yes
