---

- name: Install kube-apiserver
  copy:
    src=kube-apiserver
    dest=/usr/local/bin/
    mode=0755
  tags: install

- name: update kube-apiserver.service
  template: src=kube-apiserver.service dest=/usr/lib/systemd/system/kube-apiserver.service
  notify:
    - reload systemd
    - kube-apiserver restart service
  tags: configure

- name: reload systemd
  command: systemctl daemon-reload

- name: Start kube-apiserver
  service: name=kube-apiserver state=started
  tags: configure

- name: Enable kube-apiserver
  service: name=kube-apiserver enabled=yes
