---

- name: copy images tar to nodes
  copy:
    src=imges.tar.gz
    dest=/tmp/
    mode=0755
  tags: copy images

- name: load images
  shell:
    cd /tmp && tar xzvf imges.tar.gz && cd image && bash image.sh
  tags: load images

- name: copy controller images tar to nodes
  copy:
    src=kube-controllers-v3.1.3.tar
    dest=/tmp/
    mode=0755
  tags: copy controller images

- name: load controller images
  shell:
    cd /tmp && docker load -i kube-controllers-v3.1.3.tar
  tags: load controller images
